### ISSUE TITLE
ECONNREFUSED at UDP.onMessage

### ISSUE THREAD

**Issue by luckiday** [yoursunny/NDNts-CA#1]
Hello,

When I run the CA server on my own computer, the following error appears. 

```
 % npm start

> start
> nodemon -w .env -w src server.js

[nodemon] 2.0.7
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): .env src/**/*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
Error: recvmsg ECONNREFUSED
    at UDP.onMessage [as onmessage] (dgram.js:916:31)
[nodemon] app crashed - waiting for file changes before starting...
```

I find that this error occurs during `openUplinks()`. 

Could you help me check this issue?

Thanks

**Comment by yoursunny** [comment]
**recvmsg ECONNREFUSED** is usually a consequence of an ICMP error message.
It can happen if the program is trying to connect to a particular router that is refusing connection.
You can confirm whether this is the case with `tcpdump` and Wireshark.

You can modify `NDNTS_UPLINK` variable in `.env` file to select a different router.
The default setting given in `sample.env` is `NDNTS_UPLINK=autoconfig:` which should work in most cases, but could fail if all routers given by NDN-FCH service are unavailable or when NDN-FCH itself is down.

**Comment by luckiday** [comment]
Thanks a lot! It works now.
